# Generated by Django 5.1.3 on 2024-11-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_script', models.CharField(max_length=255, verbose_name='Caminho do Script')),
                ('frequencia', models.CharField(choices=[('D', 'Diário'), ('S', 'Semanal'), ('M', 'Mensal'), ('U', 'Uma vez')], max_length=1, verbose_name='Frequência')),
                ('tempo_repeticao', models.CharField(blank=True, choices=[('HORA', 'A cada X horas'), ('MIN', 'A cada X minutos'), ('DIA', 'A cada X dias')], help_text='Especifique o intervalo caso a frequência seja repetitiva (ex.: a cada X horas).', max_length=4, null=True, verbose_name='Intervalo de Repetição')),
                ('intervalo', models.PositiveIntegerField(blank=True, help_text='Número de horas, minutos ou dias de repetição.', null=True, verbose_name='Intervalo (X)')),
                ('hora_inicial', models.TimeField(blank=True, null=True, verbose_name='Hora Inicial')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Agendamento')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
