# Generated by Django 5.1.3 on 2024-11-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendadorScripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Apelido ou nome do script a ser executado.', max_length=100, verbose_name='Nome do Script')),
                ('responsavel', models.CharField(blank=True, help_text='Responsável pelo Script', max_length=100, verbose_name='Responsável')),
                ('caminho_script', models.CharField(help_text='Caminho completo do script a ser executado.', max_length=255, verbose_name='Caminho do Script')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='caminho_script',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='frequencia',
            field=models.CharField(choices=[('U', 'Uma vez'), ('D', 'Diário'), ('S', 'Semanal'), ('M', 'Mensal')], max_length=1, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='intervalo',
            field=models.PositiveIntegerField(blank=True, help_text='Número de horas, minutos ou dias de repetição.', null=True, verbose_name='Intervalo(X)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tempo_repeticao',
            field=models.CharField(blank=True, choices=[('DIA', 'Dia(s)'), ('HORA', 'Hora(s)'), ('MIN', 'Minuto(s)')], help_text='Especifique o intervalo caso a frequência seja repetitiva (ex.: a cada X horas).', max_length=4, null=True, verbose_name='Intervalo de Repetição'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='AgendadorScripts.scripts'),
            preserve_default=False,
        ),
    ]
