# Generated by Django 5.1.3 on 2024-11-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendadorScripts', '0003_alter_agendamento_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
    ]
